name: Build and Deploy Dataflow Flex Template

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: false
        default: "dev"

env:
  ENV: dev
  IMAGE_NAME: dataflow/csv-report-generator
  ARTIFACT_REPO: yp-bcrp-artifacts
  BUCKET: yp-bcrp-dataflow
  LOCATION: us-central1
  PROJECT_ID: back-438814
  SHORT_SHA: ${{ github.sha }}
  BUILD_SA: admin-42@back-438814.iam.gserviceaccount.com  # Asegúrate de que esta cuenta de servicio tenga los permisos necesarios

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4

      - name: Build with Maven (skip tests)
        run: mvn clean package -Dmaven.test.skip=true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Fail if secret not present
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "GCP_SA_KEY not available"
            exit 1
          fi

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          IMAGE_URI="${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}/${{ env.ENV }}:${{ env.SHORT_SHA }}"
          
          echo "Building Docker image..."
          docker build -t "$IMAGE_URI" .

          echo "Authenticating Docker to Artifact Registry..."
          gcloud auth configure-docker "${{ env.LOCATION }}-docker.pkg.dev" --quiet

          echo "Pushing image..."
          docker push "$IMAGE_URI"

      - name: Deploy Flex Template
        run: |
          IMAGE_URI="${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}/${{ env.ENV }}:${{ env.SHORT_SHA }}"

          echo "Creating Flex Template spec file in GCS..."

          gcloud dataflow flex-template build "gs://${{ env.BUCKET }}/templates/csv-report-generator/${{ env.ENV }}.json" \
            --sdk-language JAVA \
            --image-gcr-path="${IMAGE_URI}" \
            --flex-template-base-image JAVA21 \
            --metadata-file metadata.json \
            --jar target/bcrp-csv-dataflow-1.0-SNAPSHOT.jar \
            --env FLEX_TEMPLATE_JAVA_MAIN_CLASS=com.yp.bcrp.BigQueryToCSV \
            --env FLEX_TEMPLATE_JAVA_OPTIONS="-Dfile.encoding=UTF-8" \
            --service-account-email="bcrp-csv-generation-trigger@${{ env.PROJECT_ID }}.iam.gserviceaccount.com" \
            --cloud-build-service-account="projects/${{ env.PROJECT_ID }}/serviceAccounts/${{ env.BUILD_SA }}" \
            --gcs-log-dir="gs://${{ env.BUCKET }}/logs/" \
            --disable-public-ips